#! /bin/sh
# /etc/init.d/owfs
#

### BEGIN INIT INFO
# Provides:          owfs
# Required-Start:    fuse
# Required-Stop:     
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6 
# Short-Description: Mounts the 1Wire bus to /mnt/w1
# Description:       Mounts the 1Wire bus to /mnt/w1
### END INIT INFO


# Carry out specific functions when asked to by the system
case "$1" in
  start)
    echo "Mounting owfs to /mnt/w1/"
    /opt/owfs/bin/ -uall /mnt/w1/
    ;;
  stop)
    echo "you shouldn't have to stop this."
    ;;
  restart|reload)
    $0 start
    ;;
  status)
    ls /mnt/w1
    ;;
  *)
    echo "Usage: /etc/init.d/owfs {start|status}"
    exit 1
    ;;
esac

exit 0
